//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiceGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiceGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;name&quot;:&quot;Chris&quot;,&quot;score&quot;:36},{&quot;name&quot;:&quot;Andrew&quot;,&quot;score&quot;:37},{&quot;name&quot;:&quot;Chris&quot;,&quot;score&quot;:101},{&quot;name&quot;:&quot;Andrew&quot;,&quot;score&quot;:59},{&quot;name&quot;:&quot;c&quot;,&quot;score&quot;:69},{&quot;name&quot;:&quot;a&quot;,&quot;score&quot;:34},{&quot;name&quot;:&quot;a&quot;,&quot;score&quot;:49},{&quot;name&quot;:&quot;c&quot;,&quot;score&quot;:39},{&quot;name&quot;:&quot;d&quot;,&quot;score&quot;:73},{&quot;name&quot;:&quot;c&quot;,&quot;score&quot;:34},{&quot;name&quot;:&quot;b&quot;,&quot;score&quot;:133},{&quot;name&quot;:&quot;d&quot;,&quot;score&quot;:168}].
        /// </summary>
        internal static string diceGameScores {
            get {
                return ResourceManager.GetString("diceGameScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;name&quot;:&quot;c&quot;,&quot;pw&quot;:&quot;p&quot;},{&quot;name&quot;:&quot;a&quot;,&quot;pw&quot;:&quot;p&quot;},{&quot;name&quot;:&quot;b&quot;,&quot;pw&quot;:&quot;p&quot;},{&quot;name&quot;:&quot;d&quot;,&quot;pw&quot;:&quot;p&quot;}].
        /// </summary>
        internal static string userList1 {
            get {
                return ResourceManager.GetString("userList1", resourceCulture);
            }
        }
    }
}
